### ISSUE TITLE
join_text_units_to_covariate_ids失败了

### ISSUE THREAD

**Issue by hbh112233abc** [Ikaros-521/GraphRAG-Ollama-UI#11]
生成索引报错了
```shell
python -m graphrag.index --root ./ragtest --verbose --reporter rich --emit parquet
```
报错信息
```shell
join_text_units_to_covariate_ids
None
⠏ GraphRAG Indexer 
├── Loading Input (text) - 2 files loaded (0 filtered) ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 100% 0:00:00 0:00:00
├── create_base_text_units
├── create_base_extracted_entities
└── create_final_covariates
    └── create_summarized_entities
❌ Errors occurred during the pipeline run, see logs for more details.
```
是不是使用的`GraphRag`版本有问题呢,我看cli.py 65行里还有代码冲突额

**Comment by Ikaros-521** [comment]
打开详细日志看看
目前仓库的版本是实测过的，应该问题不大

**Comment by hbh112233abc** [comment]
> 打开详细日志看看 目前仓库的版本是实测过的，应该问题不大

额 我参考了其他类似的项目, 修改了`ragtest/setting.yml`的`llm.type`由`openai`改为`openai_chat`居然没报错 可以生成索引了 不知道问答会不会有问题

**Comment by Ikaros-521** [comment]
> > 打开详细日志看看 目前仓库的版本是实测过的，应该问题不大
> 
> 额 我参考了其他类似的项目, 修改了`ragtest/setting.yml`的`llm.type`由`openai`改为`openai_chat`居然没报错 可以生成索引了 不知道问答会不会有问题
> 

那刚好。新版应该有改动

**Comment by hbh112233abc** [comment]
> > > 打开详细日志看看 目前仓库的版本是实测过的，应该问题不大
> > 
> > 
> > 额 我参考了其他类似的项目, 修改了`ragtest/setting.yml`的`llm.type`由`openai`改为`openai_chat`居然没报错 可以生成索引了 不知道问答会不会有问题
> 
> 那刚好。新版应该有改动

![image](https://github.com/user-attachments/assets/00a76d12-65dc-4bdf-8cc0-bad6c26ce672)
