### ISSUE TITLE
gradio conflict  with aiofiles version 

### ISSUE THREAD

**Issue by circle79** [Ikaros-521/GraphRAG-Ollama-UI#16]
-r requirements.txt (line 24)) (0.4.6)
INFO: pip is looking at multiple versions of gradio to determine which version is compatible with other requirements. This could take a while.
ERROR: Cannot install -r requirements.txt (line 53) and aiofiles==24.1.0 because these package versions have conflicting dependencies.

The conflict is caused by:
The user requested aiofiles==24.1.0
gradio 4.38.1 depends on aiofiles<24.0 and >=22.0

To fix this you could try to:

loosen the range of package versions you've specified
remove package versions to allow pip attempt to solve the dependency conflict

**Comment by Ikaros-521** [comment]
Refer to this and install manually   https://github.com/Ikaros-521/GraphRAG-Ollama-UI/issues/10
