### ISSUE TITLE
【Linux】报错：ModuleNotFoundError: No module named 'azure'

### ISSUE THREAD

**Issue by Leonurus-free** [Ikaros-521/GraphRAG-Ollama-UI#2]
Traceback (most recent call last):

  File "/usr/lib/python3.10/runpy.py", line 187, in _run_module_as_main

    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)

  File "/usr/lib/python3.10/runpy.py", line 146, in _get_module_details

    return _get_module_details(pkg_main_name, error)

  File "/usr/lib/python3.10/runpy.py", line 110, in _get_module_details

    __import__(pkg_name)

  File "/home/GraphRAG-Ollama-UI/graphrag/index/__init__.py", line 6, in <module>

    from .cache import PipelineCache

  File "/home/GraphRAG-Ollama-UI/graphrag/index/cache/__init__.py", line 6, in <module>

    from .json_pipeline_cache import JsonPipelineCache

  File "/home/GraphRAG-Ollama-UI/graphrag/index/cache/json_pipeline_cache.py", line 9, in <module>

    from graphrag.index.storage import PipelineStorage

  File "/home/GraphRAG-Ollama-UI/graphrag/index/storage/__init__.py", line 6, in <module>

    from .blob_pipeline_storage import BlobPipelineStorage, create_blob_storage

  File "/home/GraphRAG-Ollama-UI/graphrag/index/storage/blob_pipeline_storage.py", line 12, in <module>

    from azure.identity import DefaultAzureCredential

ModuleNotFoundError: No module named 'azure'
您好，我按照您的步骤，在构建索引的时候，显示ModuleNotFoundError: No module named 'azure'。我使用的LLM是VLLM启动的Qwen2-72B-Instruct，embedding是xinference启动的 m3e-large

**Comment by Ikaros-521** [comment]
azure 相关的依赖不全吧

**Comment by Leonurus-free** [comment]
Package                               Version
------------------------------------- -----------
adal                                  1.2.7
aiofiles                              24.1.0
aiohttp                               3.9.5
aiolimiter                            1.1.0
aiosignal                             1.3.1
altair                                5.3.0
annotated-types                       0.7.0
anyio                                 4.4.0
anytree                               2.12.1
asttokens                             2.4.1
async-timeout                         4.0.3
asyncio                               3.4.3
attrs                                 23.2.0
autograd                              1.6.2
azure                                 4.0.0
azure-applicationinsights             0.1.1
azure-batch                           4.1.3
azure-common                          1.1.28
azure-core                            1.30.2
azure-cosmosdb-nspkg                  2.0.2
azure-cosmosdb-table                  1.0.6
azure-datalake-store                  0.0.53
azure-eventgrid                       1.3.0
azure-graphrbac                       0.40.0
azure-identity                        1.17.1
azure-keyvault                        1.1.0
azure-loganalytics                    0.1.1
azure-mgmt                            4.0.0
azure-mgmt-advisor                    1.0.1
azure-mgmt-applicationinsights        0.1.1
azure-mgmt-authorization              0.50.0
azure-mgmt-batch                      5.0.1
azure-mgmt-batchai                    2.0.0
azure-mgmt-billing                    0.2.0
azure-mgmt-cdn                        3.1.0
azure-mgmt-cognitiveservices          3.0.0
azure-mgmt-commerce                   1.0.1
azure-mgmt-compute                    4.6.2
azure-mgmt-consumption                2.0.0
azure-mgmt-containerinstance          1.5.0
azure-mgmt-containerregistry          2.8.0
azure-mgmt-containerservice           4.4.0
azure-mgmt-cosmosdb                   0.4.1
azure-mgmt-datafactory                0.6.0
azure-mgmt-datalake-analytics         0.6.0
azure-mgmt-datalake-nspkg             3.0.1
azure-mgmt-datalake-store             0.5.0
azure-mgmt-datamigration              1.0.0
azure-mgmt-devspaces                  0.1.0
azure-mgmt-devtestlabs                2.2.0
azure-mgmt-dns                        2.1.0
azure-mgmt-eventgrid                  1.0.0
azure-mgmt-eventhub                   2.6.0
azure-mgmt-hanaonazure                0.1.1
azure-mgmt-iotcentral                 0.1.0
azure-mgmt-iothub                     0.5.0
azure-mgmt-iothubprovisioningservices 0.2.0
azure-mgmt-keyvault                   1.1.0
azure-mgmt-loganalytics               0.2.0
azure-mgmt-logic                      3.0.0
azure-mgmt-machinelearningcompute     0.4.1
azure-mgmt-managementgroups           0.1.0
azure-mgmt-managementpartner          0.1.1
azure-mgmt-maps                       0.1.0
azure-mgmt-marketplaceordering        0.1.0
azure-mgmt-media                      1.0.1
azure-mgmt-monitor                    0.5.2
azure-mgmt-msi                        0.2.0
azure-mgmt-network                    2.7.0
azure-mgmt-notificationhubs           2.1.0
azure-mgmt-nspkg                      3.0.2
azure-mgmt-policyinsights             0.1.0
azure-mgmt-powerbiembedded            2.0.0
azure-mgmt-rdbms                      1.9.0
azure-mgmt-recoveryservices           0.3.0
azure-mgmt-recoveryservicesbackup     0.3.0
azure-mgmt-redis                      5.0.0
azure-mgmt-relay                      0.1.0
azure-mgmt-reservations               0.2.1
azure-mgmt-resource                   2.2.0
azure-mgmt-scheduler                  2.0.0
azure-mgmt-search                     2.1.0
azure-mgmt-servicebus                 0.5.3
azure-mgmt-servicefabric              0.2.0
azure-mgmt-signalr                    0.1.1
azure-mgmt-sql                        0.9.1
azure-mgmt-storage                    2.0.0
azure-mgmt-subscription               0.2.0
azure-mgmt-trafficmanager             0.50.0
azure-mgmt-web                        0.35.0
azure-nspkg                           3.0.2
azure-search-documents                11.5.0
azure-servicebus                      0.21.1
azure-servicefabric                   6.3.0.0
azure-servicemanagement-legacy        0.20.7
azure-storage-blob                    1.5.0
azure-storage-common                  1.4.2
azure-storage-file                    1.4.0
azure-storage-queue                   1.4.0
beartype                              0.18.5
blis                                  0.7.11
cachetools                            5.4.0
catalogue                             2.0.10
certifi                               2024.7.4
cffi                                  1.16.0
charset-normalizer                    3.3.2
click                                 8.1.7
cloudpathlib                          0.18.1
cloudpickle                           3.0.0
confection                            0.1.5
contourpy                             1.2.1
cramjam                               2.8.3
cryptography                          42.0.8
cycler                                0.12.1
cymem                                 2.0.8
dask                                  2024.7.0
dask-expr                             1.1.7
datashaper                            0.0.49
decorator                             5.1.1
deprecation                           2.1.0
devtools                              0.12.2
diskcache                             5.6.3
distro                                1.9.0
dnspython                             2.6.1
email_validator                       2.2.0
environs                              11.0.0
exceptiongroup                        1.2.2
executing                             2.0.1
fastapi                               0.111.1
fastapi-cli                           0.0.4
fastparquet                           2024.5.0
ffmpy                                 0.3.2
filelock                              3.15.4
fonttools                             4.53.1
frozenlist                            1.4.1
fsspec                                2024.6.1
future                                1.0.0
gensim                                4.3.2
gradio                                3.36.1
gradio_client                         1.1.0
graphrag                              0.1.1
graspologic                           3.4.1
graspologic-native                    1.2.1
h11                                   0.14.0
httpcore                              1.0.5
httptools                             0.6.1
httpx                                 0.27.0
huggingface-hub                       0.24.0
hyppo                                 0.4.0
idna                                  3.7
importlib_metadata                    8.0.0
isodate                               0.6.1
Jinja2                                3.1.4
joblib                                1.4.2
jsonschema                            4.23.0
jsonschema-specifications             2023.12.1
kaleido                               0.2.1
kiwisolver                            1.4.5
lancedb                               0.9.0
langcodes                             3.4.0
language_data                         1.2.0
linkify-it-py                         2.0.3
llvmlite                              0.43.0
locket                                1.0.0
marisa-trie                           1.2.0
markdown-it-py                        2.2.0
MarkupSafe                            2.1.5
marshmallow                           3.21.3
matplotlib                            3.9.1
mdit-py-plugins                       0.3.3
mdurl                                 0.1.2
mpmath                                1.3.0
msal                                  1.30.0
msal-extensions                       1.2.0
msrest                                0.7.1
msrestazure                           0.6.4.post1
multidict                             6.0.5
murmurhash                            1.0.10
networkx                              3.3
nltk                                  3.8.1
numba                                 0.60.0
numpy                                 1.26.4
nvidia-cublas-cu12                    12.1.3.1
nvidia-cuda-cupti-cu12                12.1.105
nvidia-cuda-nvrtc-cu12                12.1.105
nvidia-cuda-runtime-cu12              12.1.105
nvidia-cudnn-cu12                     8.9.2.26
nvidia-cufft-cu12                     11.0.2.54
nvidia-curand-cu12                    10.3.2.106
nvidia-cusolver-cu12                  11.4.5.107
nvidia-cusparse-cu12                  12.1.0.106
nvidia-nccl-cu12                      2.20.5
nvidia-nvjitlink-cu12                 12.5.82
nvidia-nvtx-cu12                      12.1.105
oauthlib                              3.2.2
ollama                                0.3.0
openai                                1.35.15
orjson                                3.10.6
overrides                             7.7.0
packaging                             24.1
pandas                                2.2.2
partd                                 1.4.2
patsy                                 0.5.6
pillow                                10.4.0
pip                                   24.1.2
plotly                                5.22.0
portalocker                           2.10.1
POT                                   0.9.4
preshed                               3.0.9
psutil                                6.0.0
py                                    1.11.0
pyaml-env                             1.2.1
pyarrow                               15.0.0
pycparser                             2.22
pydantic                              2.8.2
pydantic_core                         2.20.1
pydub                                 0.25.1
Pygments                              2.18.0
PyJWT                                 2.8.0
pylance                               0.13.0
pynndescent                           0.5.13
pyparsing                             3.1.2
python-dateutil                       2.9.0.post0
python-dotenv                         1.0.1
python-multipart                      0.0.9
pytz                                  2024.1
PyYAML                                6.0.1
ratelimiter                           1.2.0.post0
referencing                           0.35.1
regex                                 2024.5.15
requests                              2.32.3
requests-oauthlib                     2.0.0
retry                                 0.9.2
rich                                  13.7.1
rpds-py                               0.19.0
safetensors                           0.4.3
scikit-learn                          1.5.1
scipy                                 1.12.0
seaborn                               0.13.2
semantic-version                      2.10.0
setuptools                            71.1.0
shellingham                           1.5.4
six                                   1.16.0
smart-open                            7.0.4
sniffio                               1.3.1
spacy                                 3.7.5
spacy-legacy                          3.0.12
spacy-loggers                         1.0.5
srsly                                 2.4.8
starlette                             0.37.2
statsmodels                           0.14.2
swifter                               1.4.0
sympy                                 1.13.0
tavily-python                         0.3.5
tenacity                              8.5.0
textual                               0.70.0
thinc                                 8.2.5
threadpoolctl                         3.5.0
tiktoken                              0.7.0
tokenizers                            0.19.1
tomlkit                               0.13.0
toolz                                 0.12.1
torch                                 2.3.1
torchaudio                            2.3.1
torchvision                           0.18.1
tqdm                                  4.66.4
transformers                          4.42.4
triton                                2.3.1
typer                                 0.12.3
typing_extensions                     4.12.2
tzdata                                2024.1
uc-micro-py                           1.0.3
umap-learn                            0.5.6
urllib3                               2.2.2
uvicorn                               0.30.1
uvloop                                0.19.0
wasabi                                1.1.3
watchfiles                            0.22.0
weasel                                0.4.1
websockets                            11.0.3
wheel                                 0.43.0
wrapt                                 1.16.0
yarl                                  1.9.4
zipp                                  3.19.2
这是我的conda环境里面的包，我把azure 相关的依赖都安装完了，还是不行呀

**Comment by Ikaros-521** [comment]
```
aiofiles                  24.1.0
aiohttp                   3.9.5
aiolimiter                1.1.0
aiosignal                 1.3.1
altair                    5.3.0
annotated-types           0.7.0
anyio                     4.4.0
anytree                   2.12.1
asttokens                 2.4.1
async-timeout             4.0.3
asyncio                   3.4.3
attrs                     23.2.0
autograd                  1.6.2
azure-common              1.1.28
azure-core                1.30.2
azure-identity            1.17.1
azure-search-documents    11.5.0
azure-storage-blob        12.20.0
beartype                  0.18.5
blis                      0.7.11
boltons                   23.0.0
```

**Comment by Leonurus-free** [comment]
Package                   Version
------------------------- -----------
aiofiles                  24.1.0
aiohttp                   3.9.5
aiolimiter                1.1.0
aiosignal                 1.3.1
altair                    5.3.0
annotated-types           0.7.0
anyio                     4.4.0
anytree                   2.12.1
asttokens                 2.4.1
async-timeout             4.0.3
asyncio                   3.4.3
attrs                     23.2.0
autograd                  1.6.2
azure-common              1.1.28
azure-core                1.30.2
azure-identity            1.17.1
azure-search-documents    11.5.0
azure-storage-blob        12.21.0
beartype                  0.18.5
blis                      0.7.11
cachetools                5.4.0
catalogue                 2.0.10
certifi                   2024.7.4
cffi                      1.16.0
charset-normalizer        3.3.2
click                     8.1.7
cloudpathlib              0.18.1
cloudpickle               3.0.0
confection                0.1.5
contourpy                 1.2.1
cramjam                   2.8.3
cryptography              43.0.0
cycler                    0.12.1
cymem                     2.0.8
dask                      2024.7.1
dask-expr                 1.1.9
datashaper                0.0.49
decorator                 5.1.1
deprecation               2.1.0
devtools                  0.12.2
diskcache                 5.6.3
distro                    1.9.0
dnspython                 2.6.1
email_validator           2.2.0
environs                  11.0.0
exceptiongroup            1.2.2
executing                 2.0.1
fastapi                   0.111.1
fastapi-cli               0.0.4
fastparquet               2024.5.0
ffmpy                     0.3.2
filelock                  3.15.4
fonttools                 4.53.1
frozenlist                1.4.1
fsspec                    2024.6.1
future                    1.0.0
gensim                    4.3.3
gradio                    3.36.1
gradio_client             1.1.0
graphrag                  0.1.1
graspologic               3.4.1
graspologic-native        1.2.1
h11                       0.14.0
httpcore                  1.0.5
httptools                 0.6.1
httpx                     0.27.0
huggingface-hub           0.24.0
hyppo                     0.4.0
idna                      3.7
importlib_metadata        8.0.0
isodate                   0.6.1
Jinja2                    3.1.4
joblib                    1.4.2
jsonschema                4.23.0
jsonschema-specifications 2023.12.1
kaleido                   0.2.1
kiwisolver                1.4.5
lancedb                   0.9.0
langcodes                 3.4.0
language_data             1.2.0
linkify-it-py             2.0.3
llvmlite                  0.43.0
locket                    1.0.0
marisa-trie               1.2.0
markdown-it-py            2.2.0
MarkupSafe                2.1.5
marshmallow               3.21.3
matplotlib                3.9.1
mdit-py-plugins           0.3.3
mdurl                     0.1.2
mpmath                    1.3.0
msal                      1.30.0
msal-extensions           1.2.0
multidict                 6.0.5
murmurhash                1.0.10
networkx                  3.3
nltk                      3.8.1
numba                     0.60.0
numpy                     1.26.4
nvidia-cublas-cu12        12.1.3.1
nvidia-cuda-cupti-cu12    12.1.105
nvidia-cuda-nvrtc-cu12    12.1.105
nvidia-cuda-runtime-cu12  12.1.105
nvidia-cudnn-cu12         8.9.2.26
nvidia-cufft-cu12         11.0.2.54
nvidia-curand-cu12        10.3.2.106
nvidia-cusolver-cu12      11.4.5.107
nvidia-cusparse-cu12      12.1.0.106
nvidia-nccl-cu12          2.20.5
nvidia-nvjitlink-cu12     12.5.82
nvidia-nvtx-cu12          12.1.105
ollama                    0.3.0
openai                    1.36.1
orjson                    3.10.6
overrides                 7.7.0
packaging                 24.1
pandas                    2.2.2
partd                     1.4.2
patsy                     0.5.6
pillow                    10.4.0
pip                       24.0
plotly                    5.22.0
portalocker               2.10.1
POT                       0.9.4
preshed                   3.0.9
psutil                    6.0.0
py                        1.11.0
pyaml-env                 1.2.1
pyarrow                   15.0.0
pycparser                 2.22
pydantic                  2.8.2
pydantic_core             2.20.1
pydub                     0.25.1
Pygments                  2.18.0
PyJWT                     2.8.0
pylance                   0.13.0
pynndescent               0.5.13
pyparsing                 3.1.2
python-dateutil           2.9.0.post0
python-dotenv             1.0.1
python-multipart          0.0.9
pytz                      2024.1
PyYAML                    6.0.1
ratelimiter               1.2.0.post0
referencing               0.35.1
regex                     2024.5.15
requests                  2.32.3
retry                     0.9.2
rich                      13.7.1
rpds-py                   0.19.0
safetensors               0.4.3
scikit-learn              1.5.1
scipy                     1.12.0
seaborn                   0.13.2
semantic-version          2.10.0
setuptools                69.5.1
shellingham               1.5.4
six                       1.16.0
smart-open                7.0.4
sniffio                   1.3.1
spacy                     3.7.5
spacy-legacy              3.0.12
spacy-loggers             1.0.5
srsly                     2.4.8
starlette                 0.37.2
statsmodels               0.14.2
swifter                   1.4.0
sympy                     1.13.1
tavily-python             0.3.5
tenacity                  8.5.0
textual                   0.70.0
thinc                     8.2.5
threadpoolctl             3.5.0
tiktoken                  0.7.0
tokenizers                0.19.1
tomlkit                   0.13.0
toolz                     0.12.1
torch                     2.3.1
torchaudio                2.3.1
torchvision               0.18.1
tqdm                      4.66.4
transformers              4.42.4
triton                    2.3.1
typer                     0.12.3
typing_extensions         4.12.2
tzdata                    2024.1
uc-micro-py               1.0.3
umap-learn                0.5.6
urllib3                   2.2.2
uvicorn                   0.30.3
uvloop                    0.19.0
wasabi                    1.1.3
watchfiles                0.22.0
weasel                    0.4.1
websockets                11.0.3
wheel                     0.43.0
wrapt                     1.16.0
yarl                      1.9.4
zipp                      3.19.2
我再次按照您给的requirements.txt重建了conda环境，和您是一致的。但是在构建的时候还是报错：ModuleNotFoundError: No module named 'azure'。我还是不知道啥原因，求助您！

**Comment by Ikaros-521** [comment]
![Uploading image.png…]()
是有的，感觉是系统不一样 版本有出入

**Comment by Ikaros-521** [comment]
![image](https://github.com/user-attachments/assets/ef958f8e-c530-4ce6-b962-e380cf072590)
是有的，感觉是系统不一样 版本有出入

**Comment by Leonurus-free** [comment]
您是啥系统呢？方便看一下您的python环境么？

**Comment by Ikaros-521** [comment]
win11
py3.10.10
```
aiofiles==24.1.0
aiohttp==3.9.5
aiolimiter==1.1.0
aiosignal==1.3.1
altair==5.3.0
annotated-types==0.7.0
anyio==4.4.0
anytree==2.12.1
asttokens==2.4.1
async-timeout==4.0.3
asyncio==3.4.3
attrs==23.2.0
autograd==1.6.2
azure-common==1.1.28
azure-core==1.30.2
azure-identity==1.17.1
azure-search-documents==11.5.0
azure-storage-blob==12.20.0
beartype==0.18.5
blis==0.7.11
boltons @ file:///C:/b/abs_707eo7c09t/croot/boltons_1677628723117/work
brotlipy==0.7.0
cachetools==5.4.0
catalogue==2.0.10
certifi @ file:///C:/b/abs_85o_6fm0se/croot/certifi_1671487778835/work/certifi
cffi @ file:///C:/b/abs_49n3v2hyhr/croot/cffi_1670423218144/work
charset-normalizer @ file:///tmp/build/80754af9/charset-normalizer_1630003229654/work
click==8.1.7
cloudpathlib==0.18.1
cloudpickle==3.0.0
colorama @ file:///C:/b/abs_a9ozq0l032/croot/colorama_1672387194846/work
conda==23.3.1
conda-content-trust @ file:///C:/Windows/TEMP/abs_4589313d-fc62-4ccc-81c0-b801b4449e833j1ajrwu/croots/recipe/conda-content-trust_1658126379362/work
conda-package-handling @ file:///C:/b/abs_fcga8w0uem/croot/conda-package-handling_1672865024290/work
conda_package_streaming @ file:///C:/b/abs_0e5n5hdal3/croot/conda-package-streaming_1670508162902/work
confection==0.1.5
contourpy==1.2.1
cramjam==2.8.3
cryptography @ file:///C:/b/abs_8ecplyc3n2/croot/cryptography_1677533105000/work
cycler==0.12.1
cymem==2.0.8
dask==2024.7.0
dask-expr==1.1.7
datashaper==0.0.49
decorator==5.1.1
deprecation==2.1.0
devtools==0.12.2
diskcache==5.6.3
distro==1.9.0
dnspython==2.6.1
email_validator==2.2.0
environs==11.0.0
exceptiongroup==1.2.2
executing==2.0.1
fastapi==0.111.1
fastapi-cli==0.0.4
fastparquet==2024.5.0
ffmpy==0.3.2
filelock==3.15.4
fonttools==4.53.1
frozenlist==1.4.1
fsspec==2024.6.1
future==1.0.0
gensim==4.3.2
gradio==4.38.1
gradio_client==1.1.0
graphrag==0.1.1
graspologic==3.4.1
graspologic-native==1.2.1
h11==0.14.0
httpcore==1.0.5
httptools==0.6.1
httpx==0.27.0
huggingface-hub==0.23.5
hyppo==0.4.0
idna @ file:///C:/b/abs_bdhbebrioa/croot/idna_1666125572046/work
importlib_metadata==8.0.0
importlib_resources==6.4.0
intel-openmp==2021.4.0
isodate==0.6.1
Jinja2==3.1.4
joblib==1.4.2
jsonpatch @ file:///tmp/build/80754af9/jsonpatch_1615747632069/work
jsonpointer==2.1
jsonschema==4.23.0
jsonschema-specifications==2023.12.1
kaleido==0.2.1
kiwisolver==1.4.5
lancedb==0.9.0
langcodes==3.4.0
language_data==1.2.0
linkify-it-py==2.0.3
llvmlite==0.43.0
locket==1.0.0
marisa-trie==1.2.0
markdown-it-py==3.0.0
MarkupSafe==2.1.5
marshmallow==3.21.3
matplotlib==3.9.1
mdit-py-plugins==0.4.1
mdurl==0.1.2
menuinst @ file:///C:/Users/BUILDE~1/AppData/Local/Temp/abs_455sf5o0ct/croots/recipe/menuinst_1661805970842/work
mkl==2021.4.0
mpmath==1.3.0
msal==1.30.0
msal-extensions==1.2.0
multidict==6.0.5
murmurhash==1.0.10
nest-asyncio==1.6.0
networkx==3.3
nltk==3.8.1
numba==0.60.0
numpy==1.26.4
ollama==0.2.1
openai==1.35.14
orjson==3.10.6
overrides==7.7.0
packaging @ file:///C:/b/abs_ed_kb9w6g4/croot/packaging_1678965418855/work
pandas==2.2.2
partd==1.4.2
patsy==0.5.6
pillow==10.4.0
plotly==5.22.0
pluggy @ file:///C:/ci/pluggy_1648042746254/work
portalocker==2.10.1
POT==0.9.4
preshed==3.0.9
psutil==6.0.0
py==1.11.0
pyaml-env==1.2.1
pyarrow==15.0.0
pycosat @ file:///C:/b/abs_4b1rrw8pn9/croot/pycosat_1666807711599/work
pycparser @ file:///tmp/build/80754af9/pycparser_1636541352034/work
pydantic==2.8.2
pydantic_core==2.20.1
pydub==0.25.1
Pygments==2.18.0
PyJWT==2.8.0
pylance==0.13.0
pynndescent==0.5.13
pyOpenSSL @ file:///C:/b/abs_552w85x1jz/croot/pyopenssl_1677607703691/work
pyparsing==3.1.2
PySocks @ file:///C:/ci_310/pysocks_1642089375450/work
python-dateutil==2.9.0.post0
python-dotenv==1.0.1
python-multipart==0.0.9
pytz==2024.1
pywin32==306
PyYAML==6.0.1
ratelimiter==1.2.0.post0
referencing==0.35.1
regex==2024.5.15
requests==2.32.3
retry==0.9.2
rich==13.7.1
rpds-py==0.19.0
ruamel.yaml @ file:///C:/b/abs_30ee5qbthd/croot/ruamel.yaml_1666304562000/work
ruamel.yaml.clib @ file:///C:/b/abs_aarblxbilo/croot/ruamel.yaml.clib_1666302270884/work
ruff==0.5.2
safetensors==0.4.3
scikit-learn==1.5.1
scipy==1.12.0
seaborn==0.13.2
semantic-version==2.10.0
shellingham==1.5.4
six @ file:///tmp/build/80754af9/six_1644875935023/work
smart-open==7.0.4
sniffio==1.3.1
spacy==3.7.5
spacy-legacy==3.0.12
spacy-loggers==1.0.5
srsly==2.4.8
starlette==0.37.2
statsmodels==0.14.2
swifter==1.4.0
sympy==1.12
tavily-python==0.3.5
tbb==2021.11.0
tenacity==8.5.0
textual==0.70.0
thinc==8.2.5
threadpoolctl==3.5.0
tiktoken==0.7.0
tokenizers==0.19.1
tomlkit==0.12.0
toolz @ file:///C:/b/abs_cfvk6rc40d/croot/toolz_1667464080130/work
torch==2.3.1+cu121
torchaudio==2.3.1+cu121
torchvision==0.18.1+cu121
tqdm @ file:///C:/b/abs_f76j9hg7pv/croot/tqdm_1679561871187/work
transformers==4.42.4
typer==0.12.3
typing_extensions==4.12.2
tzdata==2024.1
uc-micro-py==1.0.3
umap-learn==0.5.6
urllib3==2.2.2
uvicorn==0.30.1
wasabi==1.1.3
watchfiles==0.22.0
weasel==0.4.1
websockets==11.0.3
win-inet-pton @ file:///C:/ci_310/win_inet_pton_1642658466512/work
wincertstore==0.2
wrapt==1.16.0
yarl==1.9.4
zipp==3.19.2
zstandard==0.19.0

```

**Comment by Leonurus-free** [comment]
我将linux系统更换为win系统，就没有这个问题啦。感谢作者的帮助！

**Comment by Ikaros-521** [comment]
还行
