### ISSUE TITLE
ERROR Error executing verb "text_embed" in create_final_entities: list index out of range

### ISSUE THREAD

**Issue by Ikaros-521** [Ikaros-521/GraphRAG-Ollama-UI#9]
```
17:20:01,456 openai._base_client DEBUG HTTP Request: POST http://127.0.0.1:3000/v1/embeddings "200 OK"
17:20:01,461 graphrag.llm.base.rate_limiting_llm INFO perf - llm.embedding "Process" with 0 retries took 1.562000000005355. input_tokens=176, output_tokens=0
17:20:01,463 datashaper.workflow.workflow ERROR Error executing verb "text_embed" in create_final_entities: list index out of range
Traceback (most recent call last):
  File "f:\GraphRAG-Ollama-UI\Miniconda3\lib\site-packages\datashaper\workflow\workflow.py", line 415, in _execute_verb
    result = await result
  File "F:\GraphRAG-Ollama-UI\graphrag\index\verbs\text\embed\text_embed.py", line 105, in text_embed
    return await _text_embed_in_memory(
  File "F:\GraphRAG-Ollama-UI\graphrag\index\verbs\text\embed\text_embed.py", line 130, in _text_embed_in_memory
    result = await strategy_exec(texts, callbacks, cache, strategy_args)
  File "F:\GraphRAG-Ollama-UI\graphrag\index\verbs\text\embed\strategies\openai.py", line 63, in run
    embeddings = _reconstitute_embeddings(embeddings, input_sizes)
  File "F:\GraphRAG-Ollama-UI\graphrag\index\verbs\text\embed\strategies\openai.py", line 172, in _reconstitute_embeddings
    embedding = raw_embeddings[cursor]
IndexError: list index out of range
17:20:01,464 graphrag.index.reporting.file_workflow_callbacks INFO Error executing verb "text_embed" in create_final_entities: list index out of range details=None
17:20:01,464 graphrag.index.run ERROR error running workflow create_final_entities
Traceback (most recent call last):
  File "F:\GraphRAG-Ollama-UI\graphrag\index\run.py", line 323, in run_pipeline
    result = await workflow.run(context, callbacks)
  File "f:\GraphRAG-Ollama-UI\Miniconda3\lib\site-packages\datashaper\workflow\workflow.py", line 369, in run
    timing = await self._execute_verb(node, context, callbacks)
  File "f:\GraphRAG-Ollama-UI\Miniconda3\lib\site-packages\datashaper\workflow\workflow.py", line 415, in _execute_verb
    result = await result
  File "F:\GraphRAG-Ollama-UI\graphrag\index\verbs\text\embed\text_embed.py", line 105, in text_embed
    return await _text_embed_in_memory(
  File "F:\GraphRAG-Ollama-UI\graphrag\index\verbs\text\embed\text_embed.py", line 130, in _text_embed_in_memory
    result = await strategy_exec(texts, callbacks, cache, strategy_args)
  File "F:\GraphRAG-Ollama-UI\graphrag\index\verbs\text\embed\strategies\openai.py", line 63, in run
    embeddings = _reconstitute_embeddings(embeddings, input_sizes)
  File "F:\GraphRAG-Ollama-UI\graphrag\index\verbs\text\embed\strategies\openai.py", line 172, in _reconstitute_embeddings
    embedding = raw_embeddings[cursor]
IndexError: list index out of range
17:20:01,464 graphrag.index.reporting.file_workflow_callbacks INFO Error running pipeline! details=None
```

**Comment by Ikaros-521** [comment]
更新同步最新版的源码后，暂时没有复现。
问题和 选用的llm embedding模型有关

**Comment by francis123455** [comment]
你好，请问logs.json记录的报错如下是什么问题：
{"type": "error", "data": "Error executing verb \"text_embed\" in create_final_entities: list index out of range", "stack": "Traceback (most recent call last):\n  File \"/home/ubuntu/anaconda3/envs/chatchat/lib/python3.10/site-packages/datashaper/workflow/workflow.py\", line 415, in _execute_verb\n    result = await result\n  File \"/home/ubuntu/GitProjects/graphrag-webui/graphrag/index/verbs/text/embed/text_embed.py\", line 105, in text_embed\n    return await _text_embed_in_memory(\n  File \"/home/ubuntu/GitProjects/graphrag-webui/graphrag/index/verbs/text/embed/text_embed.py\", line 130, in _text_embed_in_memory\n    result = await strategy_exec(texts, callbacks, cache, strategy_args)\n  File \"/home/ubuntu/GitProjects/graphrag-webui/graphrag/index/verbs/text/embed/strategies/openai.py\", line 62, in run\n    embeddings = _reconstitute_embeddings(embeddings, input_sizes)\n  File \"/home/ubuntu/GitProjects/graphrag-webui/graphrag/index/verbs/text/embed/strategies/openai.py\", line 171, in _reconstitute_embeddings\n    embedding = raw_embeddings[cursor]\nIndexError: list index out of range\n", "source": "list index out of range", "details": null}
{"type": "error", "data": "Error running pipeline!", "stack": "Traceback (most recent call last):\n  File \"/home/ubuntu/GitProjects/graphrag-webui/graphrag/index/run.py\", line 320, in run_pipeline\n    await inject_workflow_data_dependencies(workflow)\n  File \"/home/ubuntu/GitProjects/graphrag-webui/graphrag/index/run.py\", line 256, in inject_workflow_data_dependencies\n    table = await load_table_from_storage(f\"{id}.parquet\")\n  File \"/home/ubuntu/GitProjects/graphrag-webui/graphrag/index/run.py\", line 242, in load_table_from_storage\n    raise ValueError(msg)\nValueError: Could not find create_final_entities.parquet in storage!\n", "source": "Could not find create_final_entities.parquet in storage!", "details": null}
用的mistral和nomic-embed-text,之前使用利用graphrag包和ragtest目录在终端命令启动python -m graphrag.index --root ./ragtest是没问题的

**Comment by Ikaros-521** [comment]
> Could not find create_final_entities.parquet in storage

Could not find create_final_entities.parquet in storage

有个配置需要 使能，才会生成这个parquet，具体哪个忘记了，可以看看官方文档

**Comment by francis123455** [comment]
好的，谢谢，我再看看
        
    
        
            
        
    
         
        
            
                        ***@***.***
            
        
     
        
  
    ---- Replied Message ----
  
  
    
      
        
         From 
        
        
            ***@***.***>
            
        
      
      
        
         Date 
        
        
        8/20/2024 17:32
        
      
      
        
         To 
        
        
         
          
            ***@***.***>
            
          
        
      
      
        
         Cc 
        
        
          
            ***@***.***>
            ,
          
          
            ***@***.***>
            
          
        
      
      
        
         Subject 
        
        
              Re: [Ikaros-521/GraphRAG-Ollama-UI] ERROR Error executing verb "text_embed" in create_final_entities: list index out of range (Issue #9)
        
      
    
  


Could not find create_final_entities.parquet in storage

Could not find create_final_entities.parquet in storage
有个配置需要 使能，才会生成这个parquet，具体哪个忘记了，可以看看官方文档

**Comment by Ikaros-521** [comment]
> 好的，谢谢，我再看看 ***@***.***
> […](#)
> ---- Replied Message ---- From ***@***.***> Date 8/20/2024 17:32 To ***@***.***> Cc ***@***.***> , ***@***.***> Subject Re: [Ikaros-521/GraphRAG-Ollama-UI] ERROR Error executing verb "text_embed" in create_final_entities: list index out of range (Issue #9) Could not find create_final_entities.parquet in storage Could not find create_final_entities.parquet in storage 有个配置需要 使能，才会生成这个parquet，具体哪个忘记了，可以看看官方文档 —Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you commented.Message ID: ***@***.***>

```
claim_extraction:
  enabled: true
  description: Any claims or facts that could be relevant to information discovery.
  max_gleanings: 0
  prompt: prompts/claim_extraction.txt
cluster_graph:
  max_cluster_size: 10
community_report:
  max_input_length: 8000
  max_length: 2000
  prompt: prompts/community_report.txt
```
前面这几个来着
